#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "gogs"
name = "Gogs"
description.en = "Lightweight self-hosted Git forge"
description.fr = "Forge Git légère auto-hébergé"

version = "0.14.2~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "http://gogs.io"
demo = "https://try.gogs.io/user/login"
admindoc = "https://gogs.io/docs"
code = "https://github.com/gogs/gogs"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = true
sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gogs"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

 [resources.sources]
    [resources.sources.main]
    amd64.url = "https://github.com/gogs/gogs/releases/download/v0.14.2/gogs_v0.14.2_linux_amd64.tar.gz "
    amd64.sha256 = "0d62805cbeb870d944b05916b01dbddcb22c1b03d64236817b172ed7870bd48d"
    arm64.url = "https://github.com/gogs/gogs/releases/download/v0.14.2/gogs_v0.14.2_linux_arm64.tar.gz "
    arm64.sha256 = "72eb62dfb7cdcf42a2f57b07a405d59a6614107e4ffee153138eb60c71f4e9fe"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "gogs_v.*_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "gogs_v.*_linux_arm64.tar.gz"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["data/repositories", "data/avatars", "data/attachments"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
